### PR TITLE
Make psql command work out of box

### PR DESCRIPTION
**Pull request by mnagy**
Required setting some nev vars in the Dockerfile.

@mfojtik @hhorak @jhadvig @csrwng

### CODE REVIEW

**Comment by mnagy** [comment]
@csrwng says we can do another approach. Not setting PGUSER in Dockerfile, but setting LD_PRELOAD in dockerfile. Which is better/worse?

@bparees @mfojtik ?

**Comment by mfojtik** [comment]
i would say LD_PRELOAD is worse

**Comment by csrwng** [comment]
@mnagy I guess I misunderstood, can we do either PGUSER or LD_PRELOAD ( I thought we needed both) ? if things work ok with PGUSER, then I think  that's fine as well.

**Comment by mnagy** [comment]
@csrwng yes, we only need PGUSER and it works fine.

**Comment by mfojtik** [comment]
@csrwng @mnagy I don't think we are going to run postgresql with other user than PGUSER.
@csrwng does the artibrary UID apply to databases as well? I guess yes as we mount volumes... in that case we just need to make sure PGUSER maps to UID

**Comment by csrwng** [comment]
@mfojtik we won't know the uid until the container is running... when can we set it?

**Comment by mfojtik** [comment]
@csrwng if PGUSER will be set to 'postgres' then we just need to make sure it maps to that UID. I guess we do that.

**Comment by mnagy** [comment]
@mfojtik it will not map to it during docker exec. Do you want that? I don't think it's necessary just to run psql. I guess it might be needed for other debugging work..? Not sure.

**Comment by mfojtik** [comment]
@mnagy ok, maybe I misunderstood, so why do we need to set PGUSER? Is that needed for .bashrc to work? Is it needed for `docker exec CID /bin/bash -c psql` ? Can we just export it in .bashrc instead of setting it globally in container?

**Comment by csrwng** [comment]
@mfojtik I don't think .bashrc gets picked up when you do docker exec, but would need to check

**Comment by mfojtik** [comment]
it is not... but we are trying to make docker exec /bin/bash -c psql work
with SCL...

without  /bin/bash we will need a bash wrapper script....

**Comment by csrwng** [comment]
@mfojtik hmm, seems that maybe it could be easier to do the LD_PRELOAD? What could go wrong :-)

**Comment by mnagy** [comment]
@mfojtik PGUSER is needed for psql. Otherwise it dies with an error about user not specified.

**Comment by mnagy** [comment]
@mfojtik Good idea. We could export in .bashrc as wel. It will get picked up with bash -c, since BASH_ENV is now set.

**Comment by bparees** [comment]
so it doesn't matter that pguser isn't going to be resolvable in /etc/passwd as the current uid when we run as a random uid?

**Comment by mnagy** [comment]
Not when tou run psql, from what I've tested. No reason it should, it just
uses the user as a name when connecting.

**Comment by mfojtik** [comment]
LGTM

**Pull request merged**
