### PR TITLE
move postgres 9.4 into rhscl namespace

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@hhorak @praiskup @mfojtik fyi i'm aligning this with what was done for mongodb, are you ok with that?

**Comment by bparees** [comment]
@hhorak @praiskup @mfojtik bump

**Comment by hhorak** [comment]
@bparees I'm afraid it's not what we're going to do, the plan we have is centos/postgresql-94-centos7-candidate.

**Comment by hhorak** [comment]
The mongodb will have to move as well at some point.

**Comment by bparees** [comment]
@hhorak is the centos namespace available?  we need to put the postgres94 image somewhere.

**Comment by bparees** [comment]
@hhorak note that you're making your life complicated by having a different namespace for the centos image and the rhel image.

**Comment by hhorak** [comment]
RHSCL images based on centos might be for some time the only layered images available for centos and remember we always try to hide the fact those are based on RHSCL packages. Considering that I'd say we'd make more confusion if they would be available under rhscl/ on dockerhub.

**Pull request closed without merging**
