### PR TITLE
Add function waiting for PostgreSQL master to start

### PR DESCRIPTION
**Pull request by mnagy**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1263671

### CODE REVIEW

**Comment by bparees** [comment]
how is restarting it periodically, only to have it hit the timeout and fail again, better than a single run that waits forever?  

It will eventually start if the master appears, right?  So i see no benefit to timing out only to restart.  But it should print something to the logs to indicate what it is waiting for.

**Comment by mnagy** [comment]
@bparees I agree. And it prints out every second that it waits.

**Comment by mnagy** [comment]
..including the master FQDN

**Comment by mfojtik** [comment]
@bparees what about the case when the master never starts... you want that container run forever in loop? When the container restarts for a long time, it is a good indication that something is wrong (eg. master did not started properly).

**Comment by bparees** [comment]
> When the container restarts for a long time, it is a good indication that something is wrong (eg. master did not started properly)

that is what readiness checks are for, so if we're going to do that, it should be a readiness check, not baked into the run script.

**Comment by bparees** [comment]
or liveness rather.

**Comment by bparees** [comment]
does this not affect 9.4?

**Comment by mnagy** [comment]
@bparees yes, it does. I forgot to apply those changes there as well, good catch.

**Comment by mnagy** [comment]
Fixed, PTAL

**Pull request merged**
