### PR TITLE
Don't try to create the directory more then once

### PR DESCRIPTION
**Pull request by mnagy**
This'll make us play nicely with persistent volumes https://github.com/openshift/origin/pull/2644

### CODE REVIEW

**Comment by mnagy** [comment]
@csrwng @mfojtik PTAL

**Comment by csrwng** [comment]
LGTM, though most likely the ownership test above will succeed and there won't be a need to create a subdirectory.

**Comment by mnagy** [comment]
@csrwng I'm testing persistent volumes in the mentioned PR and this was an issue. I used nfs exports, directories owned by root with 777 permissions and got fails with mkdir not succeeding.

Merging.

**Comment by mnagy** [comment]
(Thanks :)

**Pull request merged**
